apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasky.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.mongodb.uri | quote }}
